### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by todd-lm** [c22coders/sample-profile-page#2]
We need to resolve this as this does nothing and we don't know how to fix this @apineapple

https://github.com/c22coders/sample-profile-page/commit/ed63c1f52d203cf64762be194ce005835f26eef3#commitcomment-17646039

**Comment by amazansky** [comment]
Okay. Here's what I think @apineapple wants it to do:
When the user submits the form, save all of the user's answers in `localStorage`.
I see two flaws with the way he did it.
- First, his `localStorage` syntax was wrong
- Second, even if the syntax was correct, his code would store **every option**, instead of the one the user picked.

**Comment by todd-lm** [comment]
Ok, great!
